### ISSUE TITLE
Create README.md 

### ISSUE THREAD

**Issue by Eckankar** [Eckankar/VideoTitleAdderChrome#12]
Should: 
* Describe what the extension is about.
* Link to https://chrome.google.com/webstore/detail/video-title-adder/ddpephnhacfpgcemhioaejgenlgadnnh
* Show a few screenshots

**Comment by rauenzi** [comment]
I'll work on this!

**Comment by Eckankar** [comment]
Wow, lots of activity, heh. 👍
Thanks to @rauenzi, @prestonkyles and @RyanFitzgerald. 
I will probably end up with a mix of your efforts. :)
