### ISSUE TITLE
Spiffy up the options page

### ISSUE THREAD

**Issue by Eckankar** [Eckankar/VideoTitleAdderChrome#13]
Currently it's pretty bland looking:

![image](https://cloud.githubusercontent.com/assets/21243/19290602/bf6976fa-9010-11e6-9475-ab67c8c9c3de.png)

**Comment by RyanFitzgerald** [comment]
I could take this on if you would like.

**Comment by Andrew-Hird** [comment]
#17 gave it a crack with some basic styling to build from.

**Comment by chrisgalvan** [comment]
I have sent https://github.com/Eckankar/VideoTitleAdderChrome/pull/18
<img width="526" alt="screen shot 2016-10-11 at 11 32 31 pm" src="https://cloud.githubusercontent.com/assets/1694600/19297541/8b86b564-900b-11e6-83d2-e1824608f009.png">
