### ISSUE TITLE
No LICENSE.md

### ISSUE THREAD

**Issue by prestonkyles** [Eckankar/VideoTitleAdderChrome#16]
The current code isn't licensed which may cause problems when someone wants to use the code of Video Title Adder. There are many different licenses which can be use. A list of a few of them can be seen at [Choose A License curated by Github](http://choosealicense.com/). Once choosing a license, it should be added to a **LICENSE.md** file and should probably be put in the **README.md** so that someone can easily see what the license is.

**Comment by Eckankar** [comment]
Good point. 8786735758084ce4e7e9e1746d8ea299cfc7c017 licenses the code under the MIT license.
