### ISSUE TITLE
Auto-embed of links

### ISSUE THREAD

**Issue by Eckankar** [Eckankar/VideoTitleAdderChrome#2]
Feature request: Option for automatic embedding of links.

**Comment by martinwheeler** [comment]
Hi @Eckankar, I'm keen to help out with this issue, if that's ok with you?

Just wondering what you mean by:

> automatic embedding of links

and how it should work?

**Comment by Eckankar** [comment]
Hello there, @martinwheeler! Thank you for expressing interest in the project. :)

It's been a while since I got that feature request, but I believe it refers to having an option that when enabled automatically expands the embedded player on each link, instead of having it start hidden.

**Comment by martinwheeler** [comment]
Thanks @Eckankar!

That makes sense, I'll have a look and see what I can come up with 😄

I'll create a draft PR with my thoughts and plan of attack.

**Comment by martinwheeler** [comment]
Hey @Eckankar, I've created a PR to add this feature #24. I was going to create a draft PR but I managed to get something working.
