### ISSUE TITLE
Delay on tooltip

### ISSUE THREAD

**Issue by Eckankar** [Eckankar/VideoTitleAdderChrome#3]
Option for delay on tooltip.

**Comment by estevanjantsk** [comment]
Hi @Eckankar , can you Assign this issue to me? Going to try solve this one =D.

**Comment by Eckankar** [comment]
@estevanjantsk Go for it. :) If you have any questions, just let me know.

**Comment by estevanjantsk** [comment]
Thanks! Just going to dig in after my work :+1: . Thanks! =D

**Comment by estevanjantsk** [comment]
@Eckankar Do you want the option on the option.html or just add the option delay on the qtip with 1 sec delay? =)

**Comment by Eckankar** [comment]
I would go without an option for this feature. :)

**Comment by estevanjantsk** [comment]
https://github.com/Eckankar/VideoTitleAdderChrome/pull/11 :+1:
