### ISSUE TITLE
No longer works (chrome v50 64-bit, Windows 10)

### ISSUE THREAD

**Issue by random6969** [Eckankar/VideoTitleAdderChrome#9]
The extension recently stopped working, I suspect this is either due to a recent Chrome or Youtube update.

Please investigate.

**Comment by Eckankar** [comment]
It works perfectly fine on my Chrome 50, 64-bit, Windows 7.

Do you get any errors if you look in the console (Ctrl-Shift-C), or open the background page for the extension (from chrome://extensions/) and look in the console?

**Comment by random6969** [comment]
Odd, removing the extension and readding it seems to have fixed it. Problem solved, thanks for pointing that out!
